// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0UVY9ZA2i6uZ5M27nsPGJtngWdLTzhm4',
    appId: '1:428725692163:web:8695a77138bb34f090ab36',
    messagingSenderId: '428725692163',
    projectId: 'fitstat-37dd4',
    authDomain: 'fitstat-37dd4.firebaseapp.com',
    storageBucket: 'fitstat-37dd4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM4m1Di-hTiHH3LWH-ylYh1DVEvKjh_aY',
    appId: '1:428725692163:android:a351af257f54761790ab36',
    messagingSenderId: '428725692163',
    projectId: 'fitstat-37dd4',
    storageBucket: 'fitstat-37dd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWVaPFD3SXomQUDOE-5SnpRwh8xy7Ba9s',
    appId: '1:428725692163:ios:e3fbf3117459b67190ab36',
    messagingSenderId: '428725692163',
    projectId: 'fitstat-37dd4',
    storageBucket: 'fitstat-37dd4.appspot.com',
    iosBundleId: 'com.example.fitstat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWVaPFD3SXomQUDOE-5SnpRwh8xy7Ba9s',
    appId: '1:428725692163:ios:e3fbf3117459b67190ab36',
    messagingSenderId: '428725692163',
    projectId: 'fitstat-37dd4',
    storageBucket: 'fitstat-37dd4.appspot.com',
    iosBundleId: 'com.example.fitstat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0UVY9ZA2i6uZ5M27nsPGJtngWdLTzhm4',
    appId: '1:428725692163:web:2d900f740866d99a90ab36',
    messagingSenderId: '428725692163',
    projectId: 'fitstat-37dd4',
    authDomain: 'fitstat-37dd4.firebaseapp.com',
    storageBucket: 'fitstat-37dd4.appspot.com',
  );
}
